---
- name: Ensure en_US.UTF-8 locale is present
  community.general.locale_gen:
    name: en_US.UTF-8
    state: present

- name: Ensure machine hostname is set
  ansible.builtin.hostname:
    name: "{{ baseline_hostname }}"

- name: Ensure essential tools are installed
  ansible.builtin.package:
    name:
      - zsh
      - mosh
      - tree
      - tmux
      - neovim
      - rsync
      - ncdu
      - htop
      - git
      - tmuxinator
    state: latest
