---
- name: Ensure fail2ban is installed
  ansible.builtin.package:
    name: fail2ban
    state: latest
  when: baseline_fail2ban_enabled

- name: Ensure fail2ban is enabled and running
  ansible.builtin.service:
    name: fail2ban
    enabled: true
    state: started
  when: baseline_fail2ban_enabled

- name: Ensure firewalld is installed
  ansible.builtin.package:
    name: firewalld
    state: latest
  when: baseline_firewalld_enabled

- name: Ensure firewalld service is enabled and running
  ansible.builtin.service:
    name: firewalld
    enabled: true
    state: started
  when: baseline_firewalld_enabled

- name: Ensure configured SSH port is open through firewalld
  ansible.posix.firewalld:
    port: '{{ baseline_ssh_port }}/tcp'
    permanent: true
    immediate: true
    state: enabled
  when: baseline_firewalld_enabled

- name: Ensure mosh's UDP port range is open (firewalld)
  ansible.posix.firewalld:
    port: 60000-61000/udp
    permanent: true
    immediate: true
    state: enabled
  when: baseline_firewalld_enabled

- name: Ensure desired ports are open (firewalld)
  ansible.posix.firewalld:
    port: "{{ item }}"
    permanent: true
    immediate: true
    state: enabled
  loop: "{{ baseline_firewall_open_ports }}"
  when: baseline_firewalld_enabled

- name: Ensure desired sources are whitelisted (firewalld)
  ansible.posix.firewalld:
    source: "{{ item }}"
    permanent: true
    immediate: true
    zone: trusted
    state: enabled
  loop: "{{ baseline_firewall_sources_whitelist }}"
  when: baseline_firewalld_enabled
