---
- name: Ensure all desired groups are present
  ansible.builtin.group:
    name: "{{ item }}"
    state: present
  loop: "{{ users_groups | map(attribute='name') }}"

- name: Ensure previously added groups are removed
  ansible.builtin.group:
    name: "{{ item }}"
    state: absent
  loop: >-
    {{
      current_groups | difference(users_groups | map(attribute='name'))
                     | difference(users_users | map(attribute='name'))
    }}
  when: users_remove_past_groups

- name: Ensure all desired users are present
  ansible.builtin.user:
    name: "{{ item.name }}"
    groups: "{{ item.groups }}"
    shell: "{{ item.shell | default('/bin/bash') }}"
    state: present
  loop: "{{ users_users }}"
  loop_control:
    label: "{{ item.name }}"

- name: Ensure previously added users are removed
  ansible.builtin.user:
    name: "{{ item }}"
    state: absent
  loop: "{{ current_users | difference(users_users | map(attribute='name')) }}"
  when: users_remove_past_users

- name: Add public SSH key for users that have one set
  ansible.posix.authorized_key:
    user: "{{ item.name }}"
    key: "{{ item.ssh_key }}"
  loop: "{{ users_users | selectattr('ssh_key', 'defined') }}"
  loop_control:
    label: "{{ item.name }}"
