---
users_users:
  - name: ansible
    groups:
      - sudo

# Whether to remove previously added users and groups.
users_remove_past_users: false
users_remove_past_groups: false

# Curse you Ansible and the fact I can't override 'groups'.
users_groups: []

users_tools:
  - name: dotfiles
    repository: https://github.com/d3adb5/dotfiles
    links:
      - src: zsh/zshrc
        dest: .zshrc
      - src: zsh/conf.d
        dest: .config/zsh
      - src: tmux/tmux.conf
        dest: .tmux.conf
  - name: tpm
    repository: https://github.com/tmux-plugins/tpm
    links:
      - src: .
        dest: .tmux/plugins/tpm
