name: Ansible

on: pull_request

jobs:
  ansible-lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout files in the repository
        uses: actions/checkout@v4
      - name: Run ansible-lint
        uses: ansible/ansible-lint@v24
